AllCops:
  TargetRubyVersion: 2.1
  DisplayCopNames: true

Rails:
  Enabled: true

Metrics/LineLength:
  Enabled: false

MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/Documentation:
  Enabled: false

Rails/Output:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfInsideElse:
  Enabled: false

Lint/HandleExceptions:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Rails/OutputSafety:
  Enabled: false

Rails/FilePath:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Style/IdenticalConditionalBranches:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Lint/RescueException:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false
